//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveGood.Classes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.District = new HashSet<District>();
            this.User = new HashSet<User>();
            this.User1 = new HashSet<User>();
        }
    
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public int ActionTypeID { get; set; }
        public string ActionDescription { get; set; }
        public int ActionMaxParticipants { get; set; }
        public int ActionStatusID { get; set; }
        public System.DateTime ActionRegisterDate { get; set; }
        public System.DateTime ActionStartDate { get; set; }
        public Nullable<System.DateTime> ActionFinishDate { get; set; }
    
        public virtual ActionStatus ActionStatus { get; set; }
        public virtual ActionType ActionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
    }
}
